# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae320e9260978a0a8316715b2d3508582b355a23f6c421efc1b8e0117de20820320f2269e80652eb949132badc94dda88314f037a8d3aca7cc210adb7c1501ca
  twitter_api_key: dQywDtHGw9k2v0SpOopmJH4fN
  twitter_api_secret: Xq87XcfWgXXWfk6VIWc5KNiOkvy7BpWTYRg9HOVXGswryA15ow

test:
  secret_key_base: 7947f6c7ea1c0a01f1c358468309534168ce1b8e48541f2cf36da51fbd2f01a99747d68c0a44c54bcf6a7910c61fe8db81dd736171d7bdac0ee99356b0f89090

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
